---
version: "3.4"
services:
  bitcoind:
    container_name: "bitcoind"
    image: "bitcoind:23.0"
    pull_policy: "never"
    network_mode: "host"
    volumes:
      - "bitcoind:/bitcoin/.bitcoin"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"
  electrs:
    container_name: "electrs"
    image: "electrs:0.9.9"
    pull_policy: "never"
    command: [
      "electrs", "--conf", "/data/config.toml"
    ]
    environment:
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_DB_DIR=/data
      - ELECTRS_LOG_FILTERS=INFO
      - ELECTRS_MONITORING_ADDR=0.0.0.0:4224
    network_mode: "host"
    volumes:
      - "electron-rs:/data"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"
  exporter:
    container_name: bitcoind-exporter
    image: bitcoin-prometheus-exporter:0.7.0
    restart: unless-stopped
    network_mode: host
    environment:
      BITCOIN_RPC_HOST: localhost
      BITCOIN_RPC_USER: "bitcoinrpc"
      BITCOIN_RPC_PASSWORD: "${BITCOIND_RPC_PASS}"
      REFRESH_SECONDS: 5
      LOG_LEVEL: "INFO"
    depends_on:
      - bitcoind
  clightning:
    container_name: clightning
    image: lightning:0.11.1-rtl-peerswap
    command: [
      "--plugin=/c-lightning-REST/plugin.js",
      "--plugin=/peerswap/peerswap-plugin",
      "--log-level=debug:plugin-peerswap-plugin",
      "--rest-domain=rodan.lan",
      "--network=bitcoin",
      "--bitcoin-rpcuser=bitcoinrpc",
      "--bitcoin-rpcpassword=${BITCOIND_RPC_PASS}",
      "--bitcoin-rpcconnect=localhost",
    ]
    environment:
      EXPOSE_TCP: true
    volumes:
      - "clightning:/root/.lightning"
      - "cln-rest-certs:/c-lightning-REST/certs"
    restart: unless-stopped
    network_mode: host
    depends_on:
      - bitcoind
  rtl:
    container_name: rtl
    image: rtl:peerswap
    restart: unless-stopped
    depends_on:
      - clightning
    volumes:
      - cln-rest-certs:/rest-certs:ro
      - rtl_db:/database
      - ./rtl/RTL-Config.json:/RTL/RTL-Config.json
    network_mode: host
    
volumes:
  bitcoind:
  electron-rs:
  clightning:
  cln-rest-certs:
  rtl_db:

