---
version: "3.4"
services:
  bitcoind:
    container_name: "bitcoind"
    image: "bitcoind:22.0"
    pull_policy: "never"
    network_mode: "host"
    volumes:
      - "bitcoind:/bitcoin/.bitcoin"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"
  electrs:
    container_name: "electrs"
    image: "electron-rs:0.9.5"
    pull_policy: "never"
    command: [
      "--conf", "/data/config.toml"
    ]
    environment:
      - ELECTRS_ELECTRUM_RPC_ADDR=0.0.0.0:50001
      - ELECTRS_DB_DIR=/data
      - ELECTRS_LOG_FILTERS=INFO
      - ELECTRS_MONITORING_ADDR=0.0.0.0:4224
    network_mode: "host"
    volumes:
      - "electron-rs:/data"
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1"
volumes:
  bitcoind:
  electron-rs:
